### ISSUE TITLE
viki 网页无法打开

### ISSUE THREAD

**Issue by jikchenggit** [tamlok/viki#1]
OS Version (操作系统):  Linux,  CENTOS 7.0
Note Version : Latest (最新)
Symptoms (表现): 安装好了httpd 以后，把viki 丢进去，主页打不开
How to Repro (如何复现):
自建局域网服务器。安装httpd ,开启viki 
httpd 日志：
192.168.10.144 - - [19/Nov/2018:16:50:08 +0800] "GET /js/viki.js HTTP/1.1" 200 3587 "http://192.168.10.115/" "Mozilla/5.0 (MSIE 9.0; qdesk 2.5.1279.201; Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
192.168.10.144 - - [19/Nov/2018:16:50:08 +0800] "GET /css/custom.css HTTP/1.1" 200 - "http://192.168.10.115/" "Mozilla/5.0 (MSIE 9.0; qdesk 2.5.1279.201; Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
192.168.10.144 - - [19/Nov/2018:16:50:08 +0800] "GET /js/custom.js HTTP/1.1" 200 - "http://192.168.10.115/" "Mozilla/5.0 (MSIE 9.0; qdesk 2.5.1279.201; Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
192.168.10.144 - - [19/Nov/2018:16:51:50 +0800] "-" 408 - "-" "-"
192.168.10.144 - - [19/Nov/2018:16:51:50 +0800] "-" 408 - "-" "-"
192.168.10.144 - - [19/Nov/2018:16:51:50 +0800] "-" 408 - "-" "-"
192.168.10.144 - - [19/Nov/2018:16:51:50 +0800] "-" 408 - "-" "-"
192.168.10.144 - - [19/Nov/2018:16:51:50 +0800] "-" 408 - "-" "-"
::1 - - [19/Nov/2018:16:51:52 +0800] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () (internal dummy connection)"
::1 - - [19/Nov/2018:16:51:53 +0800] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 () (internal dummy connection)"

**Comment by tamlok** [comment]
hi，

- 用的是chrome吗？
- 能否把根目录下的文件结构截图一下？

谢谢！

**Comment by tamlok** [comment]
hi，

- 用的是chrome吗？
- 能否把根目录下的文件结构截图一下？

谢谢！

**Comment by tamlok** [comment]
hi，

- 用的是chrome吗？
- 能否把根目录下的文件结构截图一下？

谢谢！

**Comment by jikchenggit** [comment]
用的是opera ,也是chrome 嘛。
![image](https://user-images.githubusercontent.com/16202628/48701559-c653e000-ec29-11e8-8b3f-2b4c4636de87.png)

**Comment by tamlok** [comment]
hi，

你需要把dist文件夹里面的文件放在服务器根目录下，其他文件都是源文件，开发用的。

或者在dist目录下启动服务器。

另外，记得把viki.html改名为index.html

**Comment by jikchenggit** [comment]
哦哦 多谢。
