### ISSUE TITLE
请问怎么放到github page上？

### ISSUE THREAD

**Issue by sqlkrad** [tamlok/viki#10]
尝试了一下访问github.io总是显示404。

**Comment by tamlok** [comment]
Hi,

具体请参考[文档](https://tamlok.gitee.io/viki/#!get_started.md)，注意必须添加文件`.nojekyll`。

可以拉取[Viki](https://github.com/tamlok/viki/tree/gh-pages)的`gh-pages`分支，这是一个托管在GitHub Pages上的例子。如果一下子部署自己的新项目有难度，可以在此基础上逐步修改。
