### ISSUE TITLE
您好，数学公式在vnote里可以正常显示，viki里面就无法显示

### ISSUE THREAD

**Issue by null-id** [tamlok/viki#12]
按照viki的教程配置好了，但是数学公式显示不正常。比如下面这段markdown代码：

```
设$N$和$X$是有限集，让$n=|N|$、$x=|X|$分别为$N$和$X$的集合大小。
```

但是这段代码就可以正常显示……很奇怪：

```
设$N$和$X$是有限集
```

使用的viki版本是dist/目录下的最新版本。

**Comment by tamlok** [comment]
Hi，

的确是有点问题。可以尝试以下在`、`两边各添加一个空格看看？如果不行再试试公式前后的`$`都添加一个空格？

后面会看看怎么修复。

**Comment by sqlkrad** [comment]
试了一下加空格好像没有效果，麻烦您有时间修复一下～多谢～～

**Comment by null-id** [comment]
您好，请问这个bug有进展吗？～～～ @tamlok

**Comment by tamlok** [comment]
Hi,

不好意思呀，最近都在搞vnotex，这个还没怎么看，我这周看看。

**Comment by null-id** [comment]
大佬别这么说，我就是问问，您有空处理～～～期待vnotex～～～

**Comment by rcocco** [comment]
类似的问题，viki里不知道为什么把文字部分当成了公式渲染，vnote和vnote导出的HTML都是正常的。
```
映射又称为算子，在不同的数学分支有不同的惯用名称。例如，从非空集$X$到数集$Y$的映射又称为$X$ 上的泛函，从非空集$X$到它自身的映射又称为$X$上的变换，从实数集（或其子集）到实数集$Y$的映射通常称为定义在$X$上的函数。
```
![捕获](https://user-images.githubusercontent.com/46603462/90328142-c20a5180-dfcc-11ea-8392-5d2cdb81429a.PNG)

**Comment by rcocco** [comment]
试了下把markdown-it-texmath更新到最新的0.8.0就正常了
