### ISSUE TITLE
无法显示出笔记本及笔记

### ISSUE THREAD

**Issue by kerHbal** [tamlok/viki#3]
笔记用的是vnote
viki是在XML文件夹底下的：
https://github.com/kerHbal/myblog/tree/master/XML
![](https://i.imgur.com/ug1INts.png)
但是打开viki点Notebook什么都没有：
https://kerhbal.github.io/myblog/XML/#!_vnote.json
![](https://i.imgur.com/MNxZ48m.png)
谢谢！

**Comment by kerHbal** [comment]
@tamlok 我加上.nojekyll文件了，似乎还是没用。。
XML文件夹下的是从某个笔记本中选的一个子文件夹，为了做对比我新建了一个与XML文件夹同级的test文件夹，其中是用vnote新建的一个笔记本，结果还是不行，，

**Comment by kerHbal** [comment]
我把子文件夹XML删了，东西都放在myblog文件夹下，是一个新的vnote笔记本，还是不行。不知道为什么。。。

**Comment by kerHbal** [comment]
@tamlok 嗯这样可以了，谢谢！

**Comment by tamlok** [comment]
Fixed in 1.0.6.
