### ISSUE TITLE
Fail to generate pages with character‘#’ in title.

### ISSUE THREAD

**Issue by SYCstudio** [tamlok/viki#4]
Here is an example:[CF538](https://sycstudio.com/#!oi/%E6%AF%94%E8%B5%9B/Codeforces%20Round%20#538%20(Div.%202).md)

**Comment by tamlok** [comment]
Hi,

It is fixed in 1.1.1, please try it out. Notice that it is not supported in the targets in `navigation.json`.

Thanks!

**Comment by SYCstudio** [comment]
It works! Thanks.
