### ISSUE TITLE
viki的显示格式与vnote格式不一致

### ISSUE THREAD

**Issue by cnkiller** [tamlok/viki#6]
vnote：2.6
操作系统：win10 64位
viki版本：v1.1.0
问题现象：
使用的md笔记，在vnote中显示为有换行，同步到viki后显示无换行。在chrome控制台也可以看到有换行的。
具体可看图：（两张图一样，随意用那个源）
https://github.com/cnkiller/imgs/blob/master/Snipaste_2019-06-21_11-00-35.png
http://chuantu.xyz/t6/702/1561086219x2073530529.png

**Comment by tamlok** [comment]
Hi,

应该是后面VNote改了默认设置，而Viki没有改，你把`viki.json`里面这一行改为true即可：

https://github.com/tamlok/viki/blob/5ea18086419643ee1839547951b345b3c3a9c5a4/dist/viki.json#L12

后面，我更新一下默认配置。

**Comment by cnkiller** [comment]
yes。解决问题，修改参数后，排版一致。
